### PR TITLE
[WiP] Packaging

### PR DESCRIPTION
**Pull request by LoicGrobol**
This is meant to fix https://github.com/UppsalaNLP/uuparser/issues/16 by adding Python packaging.

In order to conform to the structure recommended by [the official packaging guide](https://packaging.python.org/tutorials/packaging-projects/) I have reworked the directories, that can be changed back (although I don't recommend it).

The installation can be tested with 

```console
pip install --no-cache-dir cython
pip install --no-cache-dir --extra-index-url https://test.pypi.org/simple uuparser
```

(`--no-cache-dir` to be correctly simulate a fresh install, separate Cython install required for Python > 3.7 until DyNet either release a new version integrating https://github.com/clab/dynet/pull/1608 or release Python 3.8 wheels)

## Other changes:

- Remove the outdated Pipenv files pertaining to Python 2.7
- Add Github's Python gitignore
- Add a console entry point: once the package is installed, the parser can now be called directly from command line by `uuparser`
- Some string interpolation is done with f-strings, making this `python >= 3.6`, if this is an issue, it can be changed back.
- Rename the main source dir (and hence the package name) from `barchybrid` to `uuparser`, which seemed more fitting but this is purely cosmetic and easy to change
- Add a very basic smoke test to see if we can train a model on a tiny corpus (run with [`tox`](https://tox.readthedocs.io))
- Fix running with path containing space (which previously crashed the evaluation)

## ToDo

- [x] update doc/readme
- [x] validate metadata
- [x] test if everything runs correctly (maybe add unit/integration/smoke tests along the way)
- [x] test release and install in a fresh env (via test.pypi)

### CODE REVIEW

**Comment by LoicGrobol** [comment]
@mdelhoneux (or someone else) Can you check if the metadata in [setup.cfg](https://github.com/LoicGrobol/uuparser/blob/packaging/setup.cfg) are correct?

**Comment by mdelhoneux** [comment]
> @mdelhoneux (or someone else) Can you check if the metadata in [setup.cfg](https://github.com/LoicGrobol/uuparser/blob/packaging/setup.cfg) are correct?

Yep looks good! This is great, thanks!

**Comment by LoicGrobol** [comment]
@mdelhoneux Cool, then unless there are specific things you'd like to test, this is ready to merge :-) I will delete the test upload on test.pypi and it will just need [two commands](https://twine.readthedocs.io/en/latest/#using-twine) to upload it on pypi, it's probably better if it's done by a maintainer than by me

**Comment by LoicGrobol** [comment]
Woops, found a tiny bug, please don't merge just yet

**Comment by mdelhoneux** [comment]
ok, cool!

**Comment by LoicGrobol** [comment]
Ok, ready to merge now!

**Pull request merged**
