### PR TITLE
Use a proper logging mechanism

### LINKED ISSUE #18: Better logging mechanism
Here I go again 🙂

For now logging is done directly via `print` calls which makes it hard to embed the parser in another application or to add a `--quiet` option…
Would you be open to a PR that changes that to proper logging calls? Preferably with [loguru](https://github.com/Delgan/loguru), which has a nice API, but if adding a dependency is somehow an issue it can be done with the clunkier `logging` from stdlib.

Also if these issues become too annoying or too time-consuming at some point do tell me!

### PR DESCRIPTION
**Pull request by LoicGrobol**
Fix #18 

## ToDo

- [x] Switch the main operations to loguru
- [ ] Switch the standalone scripts to loguru
- [x] Add a verbose/quiet switch
- [x] Add the option to log to a file
- [x] Add a progressbar display for training to replace the training progress in default (non-verbose, non-quiet) mode

## Asides

- Adds a dependency on [loguru](https://loguru.readthedocs.io), to my knowledge the currently nicest python logging library and [tqdm](https://tqdm.github.io).
- Also switch many string formatting from C-style % format and string sums to f-string interpolation
- [DyNet](https://github.com/clab/dynet/issues/1528) messages on import are still here even in quiet mode. They [could probably](https://stackoverflow.com/a/17954769/760767) be suppressed if we tried hard enough but is might be too much effort for a limited gain.
- The warning caused by using `dy.parameter` somewhat disrupts the progressbar for the first epoch (nothing awful) and could be solved by stopping using `dy.parameter` (using [the new DyNet 2.1 API](https://github.com/clab/dynet/pull/1233)) but this is out-of-scope here and will be done in another PR

## Previews

Normal mode:

image

With the `--verbose` flag:

image

With the `--quiet` flag: only DyNet unfortunate output

Animated preview:

[asciicast](https://asciinema.org/a/ijLDLbvu1QixxqflsD8jDoHPb)

### CODE REVIEW

**Comment by mdelhoneux** [comment]
Looks great! Did you want me to check something in particular?

**Comment by LoicGrobol** [comment]
@mdelhoneux Maybe two things :

1. The output now looks like this in default mode

   image

   And like this in verbose mode

    image

   which is my usual logging setup. Are you okay with the look of it? Now that I look at it, the verbose mode is maybe too verbose 🤔.

2. In default mode, we no longer display the training progress every 100 sentences but only after each epoch. This can of course be reverted. Another option would be to display a progressbar indicator, which would be more compact in console.

**Comment by mdelhoneux** [comment]
Looks good! Nitpicky comment, I don't know how easy it would be to change, but would it be possible to align the text in verbose mode? I mean that the F of 'Finished epoch 1' appears exactly under the T of 'Total training time'. 
2. I do prefer to have a sense of how long it's taking by default so I would keep printing the progress although it can be for more than 100 sentences? A progressbar would be very cool of course :)

**Comment by LoicGrobol** [comment]
> I don't know how easy it would be to change, but would it be possible to align the text in verbose mode? I mean that the F of 'Finished epoch 1' appears exactly under the T of 'Total training time'.

I think I will just remove the file@line part, which will make it both more compact and aligned without removing any crucial information

> I do prefer to have a sense of how long it's taking by default so I would keep printing the progress although it can be for more than 100 sentences? A progressbar would be very cool of course :)

Progressbar it is :-)

**Comment by LoicGrobol** [comment]
I think it's ready now. I did not change the standalone scripts, but it doesn't feel terribly important :-)

**Comment by mdelhoneux** [comment]
Yep! This is beautiful, thanks! About the dynet deprecated warning, I have not modified it so far to keep it backwards compatible but I think at this point we can go ahead (we lost backwards compatibility by moving to python 3 anyway)

**Pull request merged**
